services:
  app-nextauth-sample:
    container_name: app-nextauth-sample
    build:
      context: ../app
      dockerfile: ../app/Dockerfile
      target: dev
    ports:
      - 3301:3301
    environment:
      - NEXT_PUBLIC_BFF_URL=${NEXT_PUBLIC_BFF_URL}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COGNITO_CLIENT_SECRET=${COGNITO_CLIENT_SECRET}
      - COGNITO_ISSUER=${COGNITO_ISSUER}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    volumes:
      - ../app:/app
      - app-nextauth-sample_node_modules:/app/node_modules
    networks:
      - apps
  bff-nextauth-sample:
    container_name: ${BFF_CONTAINER_NAME}
    build:
      context: ../bff
      dockerfile: ../bff/Dockerfile
      target: dev
    ports:
      - 3302:3302
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    volumes:
      - ../bff:/app
      - bff-nextauth-sample_node_modules:/app/node_modules
    networks:
      - apps

networks:
  apps:
    driver: bridge

volumes:
  app-nextauth-sample_node_modules:
  bff-nextauth-sample_node_modules:
